### ISSUE TITLE
Difficulty is 0* on all beatmaps

### ISSUE THREAD

**Issue by Subjecter** [Flutterish/Hitokori#25] opened 2021-11-17 15:55 UTC
I have recently installed **Hitokori**
Before installing **Hitokori** though, I had uninstalled every **Osu** I had Being / **Lazer** & Normal **Osu!**

Ran both clients (Not at the same time)
No issues so I was glad

But after downloading **Hitokori** and placing it to the rulesets folder, I had launched **Lazer** expecting it to be fixed.

The previous time I had downloaded **Hk** It worked completely fine Until I ran into some random bug and ever since then bm's are now ranked as zero stars and cannot be played

It pisses me off because I love this custom gamemode, But cannot play it :C

Mind you - I downloaded the .dll file not the other files

**Comment by Coppertine** [comment] 2021-11-17 15:58
This is a simple fix, I'll make a PR... although I do know that Flutterish is doing a redo of the entire ruleset or smth.

**Comment by Subjecter** [comment] 2021-11-17 16:00
That would be absolutely awesome, I just don't know what to do to fix this right now. it would be great to share how to fix for right now at least.

**Comment by Coppertine** [comment] 2021-11-17 16:02
Just checking, it's already fixed in the normal version, just gonna ping the ruleset owner to fix the issue.

**Comment by Flutterish** [comment] 2021-11-17 22:34
Yeah, the issue is that lazer had an update which made some rulesets incompatible, I will update immediately. However the difficulty calculator is a weird issue since nothing really changed but for whatever reason the SR values are ~0.14*. I think I will just revert to rescaling the base SR of converted beatmaps for the time being, since a remaster is in the works anyway and it will have this feature properly implemented.

**Comment by Flutterish** [comment] 2021-11-17 22:44
Hito 0.18.12 resolves this

**Closed by Flutterish** 2021-11-17 22:44 UTC

**Comment by Flutterish** [comment] 2021-11-17 22:49
@Subjecter if you are interested what's coming with the remaster, here are some videos - [Duet](https://www.youtube.com/watch?v=w9-SpdeJIOw), [Regular](https://www.youtube.com/watch?v=NiYi1VLhHvQ) and [Solo](https://www.youtube.com/watch?v=SgVMz_lg_o4).
